services:
  mysql:
    container_name: "mysql"
    image: "docker.io/library/mysql:9.1"
    environment:
      MYSQL_ROOT_PASSWORD: "!d!e6mpuhKjicChYxhBOog"
      MYSQL_DATABASE: "employees"
    volumes:
    - "emp-apphost-f7f21a5b02-mysql-data:/var/lib/mysql"
    ports:
    - target: 3306
      published: 3306
    restart: unless-stopped
  empployeedbmanager:
    container_name: "empployeedbmanager"
    image: "empployeedbmanager:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__employees: "Server=mysql;Port=3306;User ID=root;Password=!d!e6mpuhKjicChYxhBOog;Database=employees"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  employeeapi:
    container_name: "employeeapi"
    image: "employeeapi:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__employees: "Server=mysql;Port=3306;User ID=root;Password=!d!e6mpuhKjicChYxhBOog;Database=employees"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
  employee-portal:
    container_name: "employee-portal"
    image: "employee-portal:latest"
    environment:
      NODE_ENV: "development"
      services__employeeapi__http__0: "http://employeeapi:8080"
      PORT: "8000"
    ports:
    - target: 8000
      published: 8000
    restart: unless-stopped
volumes:
  emp-apphost-f7f21a5b02-mysql-data: {}
